#!/bin/bash

# Check if $PYFILE is set
[ -z "$PYFILE" ] && { echo "Error: Environment variable \$PYFILE is not set."; exit 1; }

# Check if the Python file exists
[ ! -f "$PYFILE" ] && { echo "Error: Python file '$PYFILE' not found."; exit 1; }

# Run the Python script
python "$PYFILE"
